### ISSUE TITLE
Move serial IO from pins 2 and 3 to 9 and 10

### ISSUE THREAD

**Issue by N4IRS** [wojciechk8/MMDVM_pog#1]
I see you moved the communications port from PA2 and PA3 to PA9 and 10. I edited the IOSTM_CMSIS.cpp and changed 2 to 9 and 3 to 10. I can flash the LED, but I can not communicate with the processor. Did I miss something?

73, Steve N4IRS

**Comment by wojciechk8** [comment]
Yes, I did it because previously I forgot to check which USART pins can be used to communicate with internal bootloader. Later it turned out that PA2, PA3 (USART2) couldn't be used for this purpose, so I changed them to PA9, PA10 (USART1). I suspect that you've changed only pins configuration in the IOSTM_CMSIS.cpp, but it's also required to change the actual USART in the SerialSTM_CMSIS.cpp. I've already done it and I'm attaching this file, but I haven't tested it yet. After I check if it works, I will do a pull request to the main MMDVM repository (now I'm waiting for ordered PCBs).

Regards
Wojciech

[USART1_fix.zip](https://github.com/wojciechk8/MMDVM_pog/files/1007351/USART1_fix.zip)

**Comment by N4IRS** [comment]
Wojciech,
You are correct, I did try changing the pin numbers, but realized that the USART needed to be change. I just tried your changes. MMDVMHost still can not communicate with the processor. I am out of time for the next few days. When I get back I'll work with you to test and refine what is needed. Thank you again for your help.

73, Steve N4IRS

**Comment by N4IRS** [comment]
Wojciech,
I put the CPU in BOOT_0 and reset the CPU. This is the result I get. 
Interface serial_posix: 57600 8E1
Version      : 0x22
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0418 (STM32F105xx/F107xx)
RAM        : 64KiB  (4096b reserved by bootloader)
Flash      : 256KiB (size first sector: 2x2048)
Option RAM : 16b
System RAM : 18KiB

No doubt I can talk to the CPU via the USART in boot mode. I applied the code changes you posted. The compile but MMDVMHost can not communicate with the modem.
73, Steve N4IRS

**Comment by wojciechk8** [comment]
Steve,
Maybe I missed something in USART configuration, I checked the firmware only with the previous PCB revision (on USART2). Now I have the new PCB, but the parts will arrive next week and then I'll test it and commit a fix.

Regards
Wojciech

**Comment by wojciechk8** [comment]
Hi Steve,
I managed to run the firmware. There was a mistake in USART2Init function.
Instead of:
```
RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
USART2->BRR = USART_BRR(36000000UL, speed);
```
it should be:
```
RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
USART1->BRR = USART_BRR(72000000UL, speed);
```
I've already done a pull request to the main repository, so you should be able to pull the corrected code from there soon. Please check this on your hardware and tell me if there are any problems.

Regards
Wojciech

**Comment by N4IRS** [comment]
Wojciech,
I applied your patches and I can now communicate with the MMDVM via the USART. Thanks! I will start testing using it with a radio in DMO this weekend. THANKS!
Steve

**Comment by wojciechk8** [comment]
That's great!
I've just finished assembling 10 boards.
Paweł SQ6POG had tested them in duplex mode with Motorola GM340/350/950 and it worked great.

73 and good luck
Wojciech
